defaults: &defaults
  placeholder: true

development:
  <<: *defaults
  environment_name: development
  nested:
    content: 100
    irrelvant: yes
development_alternate:
  nested:
    content: 102
test:
  <<: *defaults
  environment_name: test
  nested:
    content: 116
